name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.10.16', '3.12.0']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python }}      

      - name: Install dependencies (incl. dev)
        run: |
          uv sync --extra dev

      - name: Check pytest
        run: uv run pytest --version

      - name: pytest
        run: uv run pytest --cov=skpm tests

      - name: Statistics
        if: success()
        run: |
          uv run coverage report
          uv run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          name: Coverage
          fail_ci_if_error: false
