name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.10']
        os: [ubuntu-latest] #, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
    
      - name: Install Python dependencies
        run: |
          poetry install
      
      - run: |
          source $VENV
          pytest --version

      - name: pytest
        run: poetry run pytest --cov=skpm tests

      - name: Statistics
        if: success()
        run: |
          poetry run coverage report
          poetry run coverage xml

      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        # see: https://github.com/actions/toolkit/issues/399
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          # flags: cpu
          name: Coverage
          fail_ci_if_error: false